### PR TITLE
helm: fix arbitrary file overwrite in fuzz target

### PR DESCRIPTION
**Pull request by catenacyber**
CC @AdamKorcz ;-)

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Thanks @catenacyber -- could you sign off your commit?

**Comment by catenacyber** [comment]
Like this ?

**Comment by catenacyber** [comment]
Ok, so here is another proposal force-pushed

**Comment by AdamKorcz** [comment]
> Ok, so here is another proposal force-pushed

Perfect, thanks!

**Pull request merged**
